
package com.tunav.tunavmedi.dal.abstraction;

import android.graphics.drawable.Drawable;

public abstract class AuthenticationHandler {
    public String getName() {
        return null;
    }

    /*
     * @return the authentication token generated by the server after a
     * successful authentication.
     */

    public Drawable getPhoto() {
        return null;
    }

    public boolean islogged() {
        return false;
    }

    /*
     * Check if the credential given by the user are correct (userID) or not
     * (null).
     * @param login User login.
     * @param passhash cryptographic hash of the base64 password encoding.
     * @return userID if authentication is successful, else null.
     */
    public Integer login(String username, String password) {
        return null;
    }

    public void logout() {

    }
}
