
package com.tunav.tunavmedi.dal.abstraction;

public abstract class AuthenticationHandler {
    public static boolean isAuthenticated = false;

    public String getDisplayName() {
        return null;
    }

    /*
     * @return the authentication token generated by the server after a
     * successful authentication.
     */

    public String getError() {
        return "Authentication Failed! Wrong id/password combination.";
    }

    public String getPhoto() {
        return null;
    }

    public boolean getStatus() {
        return isAuthenticated;
    }

    /*
     * Check if the credential given by the user are correct (userID) or not
     * (null).
     * @param login User login.
     * @param passhash cryptographic hash of the base64 password encoding.
     * @return userID if authentication is successful, else null.
     */
    public void login(String username, String password) {
        setStatus(true);
    }

    public void logout() {
        setStatus(false);
    }

    protected boolean setStatus(boolean status) {
        isAuthenticated = status;
        return isAuthenticated;
    }
}
