package com.tunav.tunavmedi.abstraction;

public abstract class AuthenticationHandler {
    /*
     * Check if the credential given by the user are correct (userID) or not
     * (null).
     * 
     * @param login User login.
     * 
     * @param passhash cryptographic hash of the base64 password encoding.
     * 
     * @return userID if authentication is successful, else null.
     */
    public Integer authenticate(String login, String password) {
	return null;
    }

    /*
     * @return the authentication token generated by the server after a
     * successful authentication.
     */

    public void revokeToken(byte[] token) {
    }

    public byte[] requestToken() {
	return null;
    }

    public void deauthenticate() {

    }

    public boolean check() {
	return false;
    }
}
